# Generated by Django 5.2.7 on 2025-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicalpasswordresetcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='type',
            field=models.CharField(choices=[('user', 'Usuário'), ('manager', 'Gestor'), ('admin', 'Administrador')], default='user', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('user', 'Usuário'), ('manager', 'Gestor'), ('admin', 'Administrador')], default='user', max_length=10, verbose_name='Tipo'),
        ),
    ]
